# Generated by Django 3.2.9 on 2023-12-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20231222_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='account',
        ),
    ]
